# Generated by Django 4.2 on 2023-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dsensor",
            fields=[
                (
                    "time",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("humi", models.FloatField()),
                ("tem", models.FloatField()),
            ],
            options={
                "db_table": "dsensor",
            },
        ),
    ]
