# Generated by Django 4.2 on 2023-06-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0002_dsensor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dsensor",
            table="sensor_data",
        ),
    ]
