# Generated by Django 4.2 on 2023-06-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0004_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dsensor",
            table="dsensor",
        ),
    ]
