# Generated by Django 4.2.1 on 2023-06-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_alter_dsensor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dsensor',
            table='dsensor_web',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_data_web',
        ),
    ]
