# Generated by Django 4.2.1 on 2023-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_user_id_alter_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
