# Generated by Django 4.2.2 on 2023-06-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
